[workspace]
authors = ["kaspermunch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge", "bioconda", "gwforg", "munch-group"]
name = "relate1Kgenomes"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
bcftools = "*"
biopython = "*"
curl = "*"
git = "*"
git-lfs = "*"
gwf = "*"
ipykernel = "*"
numpy = "*"
pandas = "*"
pytables = "*"
pyyaml = "*"
tskit = "*"
wget = "*"
yaml = "*"
zlib = "*"
nbclient = ">=0.10.2,<0.11"
jupyterlab = ">=4.4.5,<5"
seaborn = ">=0.13.2,<0.14"
geneinfo = ">=5.3.17,<6"
genominterv = ">=2.0.14,<3"
nbdime = ">=4.0.2,<5"
