project:
  type: manuscript
  output-dir: ../_book/manuscript

manuscript:
  article: index.qmd

format:
  html: default
  docx: default
#  jats: default

  pdf:
    # latex-clean: false
    documentclass: scrbook
    pdf-engine: pdflatex
    papersize: A4
    toc: true
    toc-depth: 2
    toc-title: "Table of contents"
    lof: false
    lot: false
    fig-align: center
    geometry:
      - left=2.54cm
      - right=2.54cm           
      # - inner=3cm
      # - outer=4cm
      # - top=3cm
      # - bottom=4cm
      # - headsep=22pt
      # - headheight=11pt
      # - footskip=33pt
      # - ignorehead
      # - ignorefoot
      # - heightrounded
    linestretch: 1.0
    number-sections: true
    highlight-style: kate 
    tbl-cap-location: bottom
    include-in-header:
      - file: header_extra.tex

notebook-links: false

lightbox: true

execute:
  freeze: auto

bibliography: ../references.bib
